### ISSUE TITLE
Remove Disposition

### ISSUE THREAD

**Issue by CepheiA2** [p4535992/foundryvtt-token-factions#19]
Hi, i think would be nice to add an option to remove the default disposition's square when using token faction.

**Comment by p4535992** [comment]
Sorry I didn't understand , can't you just change the settings "Generate token color from " ?

**Comment by CepheiA2** [comment]
Sorry, i mean would be nice a feature that allow to remove the foundryVTT token disposition while using the Faction one.
![Immagine 2022-10-31 002632](https://user-images.githubusercontent.com/85868381/198907073-499c7674-fccf-4ef2-9292-1d9041358be8.png)
In this example i would like to remove the yellow square of disposition

**Comment by p4535992** [comment]
A ok that job is done from "https://github.com/kandashi/Border-Control" i did not not provided that in this module. For now I am waiting for kandashi to come back to update his modules.

**Comment by CepheiA2** [comment]
ah, ty!


Il giorno lun 31 ott 2022 alle ore 08:13 4535992 ***@***.***>
ha scritto:
