### ISSUE TITLE
Token factions should considere visibility status

### ISSUE THREAD

**Issue by CePeU** [p4535992/foundryvtt-token-factions#22]
If I give a color to tokens according to factions like friendly, enemy etc. token faction works great and enhances the overview I and the players have when a lot of icons are on the game board.

As a GM though I want to place new tokens on the board (ALT and draw an icon on the board) or I might make a token invisible when they lay in ambush. As a GM token factions helps to keep those token organized but as a player I should not be able to see those invisible icons. Token faction keeps drawing a faction color around those invisble tokens and thus reveals them.

A new setting "Show invisible faction colors only to GM"  would be a nice improvement.

**Comment by kevinbailey25** [comment]
Not sure if this is similar or not, but you can see the Token Factions through fog of war and when characters are not in line of sight. I couldn't find a setting or anything. Hope this could be added. Would be awesome to not show the factions unless the token itself is visible.

**Comment by amcvfx** [comment]
I have the same issue. It used to only show the border for visible tokens but now all of them are visible. Border Control (which does a similar thing) also causes the same issue.

**Comment by p4535992** [comment]
The problem is fvtt10....and the new logic he implemented I was able to handle the use cases on the player side but unfortunately the GM when he checks a token will see the faction designs of the tokens.

![img](https://github.com/p4535992/foundryvtt-token-factions/raw/master/wiki/bug_gm_can_see.gif)

Even with this "problem" now the module should be usable, unfortunately I am not a PIXI expert.

**Comment by amcvfx** [comment]
Thanks for the update. This does fix all factions visible to players but unfortunately it doesn't display a faction until the player hovers over the token (except for their owned tokens):
![tokenFactions](https://user-images.githubusercontent.com/35099081/203754599-0e6df1ef-5f61-4904-bb23-2385c6235f2a.gif)

**Comment by p4535992** [comment]
Should be finally fixed 0.3.8. Try out and let me know it.

**Comment by kevinbailey25** [comment]
> Should be finally fixed 0.3.8. Try out and let me know it.

It's working perfectly! We happened to have to cancel our last session where I was gonna use this due to a player being sick. So I'm super excited to be able to use it for our upcoming session. 

Thanks so much for a great module!
