### ISSUE TITLE
[BUG] When Token Factions and Token Auras are enabled, token nameplates are always visible even when Display Name is set to "Never Displayed"

### ISSUE THREAD

**Issue by schmickers1978au** [p4535992/foundryvtt-token-factions#23]
**Module Version:** Token Factions v0.3.8
**Module Version:** Token Auras v2.1

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
When Token Factions and Token Auras are both enabled, token nameplates are displayed even when the Display Name option under token settings is set to "Never Displayed".
Disabling either module returns Foundry to its expected behaviour so it seems to be an interaction between these two modules. 

**To Reproduce**

1. Fresh foundry install
2. Install Token Auras and Token Factions modules and dependencies
3. Create a token and set it to "Display Name: Never"
4. Token nameplate is visible.

**Expected behavior**
Token nameplates should respect the core token setting and be displayed or hidden accordingly. 

**Screenshots**

![image](https://user-images.githubusercontent.com/120413059/207130279-054ace8a-a500-4e79-adb9-00614e5babb3.png)
![image](https://user-images.githubusercontent.com/120413059/207130367-8a56099f-d9de-449b-9e1f-cb0c279a362e.png)

**Browser:**
Chrome 

**Foundry Version:** 
Foundry Virtual Tabletop: Version 10, 10.291
Game System: dnd5e, 2.0.3
Active Modules: 4
Performance Mode: 1

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
GPU: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1920 x 1080 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 1 | Ambient Sounds: 0 | Tiles: 30 | Tokens: 6

Actors: 231 | Items: 20 | Journal: 23 | Rollable Tables: 7 |
Playlists: 16 | Compendium Packs: 27 | Chat Messages: 0

**Additional context**
Log file of loading map: https://pastebin.com/ptLc5BQJ

**Comment by p4535992** [comment]
@schmickers1978au  should be fixed on my side with 0.3.10
