### ISSUE TITLE
Feature Request: Draw borders on top

### ISSUE THREAD

**Issue by Zamrod** [p4535992/foundryvtt-token-factions#6]
The old version of token factions had the ability to draw the borders on top and change the radius of the borders so you could use them to cover up circular borders on the tokens with faction based ones. Also, with the beveled borders feature, they looked very nice. This feature seems to have been lost in the change over to the new version. I'd like to see it return.

**Comment by CepheiA2** [comment]
I would love to be able to have faction borders drawn over the token, I'm currently playing with version 0.3.1 of this module which supported this feature, Is there any chance this will work again?

**Comment by p4535992** [comment]
Should be fixed with version 0..4.6 for v11

**Comment by Zamrod** [comment]
This has not been fixed. I do not see the option in the settings at all to enable borders on top. If you set a circular border and give it a negative radius, it goes underneath the token and can't be seen at all.
